### PR TITLE
Design TearDown Collaborative Microverse Project

### PR DESCRIPTION
**Pull request by Emmanuelaaron**
In this project, we did the following
- Utilised CSS grid and flexbox to design it.
- Utilised different shades of grey to build contrast among the different elements of the page to build an engaging user experience

### CODE REVIEW

**Review by nikasulo — CHANGES_REQUESTED** [review]
# Under Review By Tolulope Olusakin(TSE)
Please check on this in a few minutes for some feedback! :+1:

**Review by nikasulo — CHANGES_REQUESTED** [review]
# Great work @Emmanuelaaron and @guirecordon :rocket: 
This is really great work! Please consider that the purpose of this project is to create a 'mockup' of sorts for the original site using grey colored boxes to mark the elements in order of the importance in which you are perceive them and not a replica of the website. Please take a look at [this](https://rawcdn.githack.com/carlosprietobarron/smashingmag/2af4d72ed7e3f7e857d8bdc8e2b8637ec1a6bf33/index.html) and use it as an example

##### Think I missed something? Need some help with this or any of your projects? Please feel free to reach out to me on [Twitter](https://twitter.com/oluwadamilareo_) or [Instagram](https://instagram.com/oluwadamilare_olusakin), even if you just want to chat and I will respond to you as soon as I can.

**Review by addod19 — CHANGES_REQUESTED** [review]
## Status: Require changes 🔴

Hi @Emmanuelaaron AND @guirecordon, you have done really great with this project 👍 , However, there is only one fix for the project to be approved. Find comment below:
- ```In the 3 rows``` section, each row contains 3 articles and each article takes 1/3 of the screen width. Let us kindly follow the pattern.
cp
Currently, this is what we have 
cp1
Let us also check the width of the remaining 2 rows. Each article should have 1/3 of the width.
Let us check the [original](https://www.smashingmagazine.com/) page for reference. So that we understand what it means.

Kindly make these changes and submit another code review 😄 
_Happy coding_ 👨‍💻 
[Daniel Larbi Addo](https://www.linkedin.com/in/daniel-larbi-addo-9738b0128/)

**Review by addod19 — CHANGES_REQUESTED** [review]
## Status: Require changes 🔴

Hi **Team** we are almost there, we did great fixing the change but there are 2 things we should take note.
- Kindly remove ```line 246 - 267```. Remember, the focus is on 3 rows, not 4 as it is currently.
- The second row should have 3 columns of equal width as in the screenshot below
miss
Currently, we have 2 columns, let us change it to 3 columns.
```Our version```
miss2


Kindly fix these changes and submit another code review 👐 
Good luck with your next submission 👨‍💻 
_Happy coding_
[Daniel Larbi Addo](https://www.linkedin.com/in/daniel-larbi-addo-9738b0128/)

**Comment by guirecordon** [comment]
Thank you for pointing that out. We just fixed the issues.

**Comment by SofiBretz** [comment]
### Changes required ♻️
### Hello team 🌟

Great work on this project, but you need to fix the issues below before moving on ⬇️

I apologize that the last TSE doesn't mark you some important things as a request changes, but you have to make the project with the same columns and rows as the original page. 

- [ ] Consider made 4 columns and 1 row here, as the original page: 




- [ ] Missing an entire section here, consider add this section, follow the design of the original page:





- [ ] Consider follow the columns and the rows as the original page:




- [ ] Consider following the columns and rows as the original page.

_**After making the required changes please submit a new code review request**_
Good luck! 🍀

SofiBretz.

**Pull request closed without merging**
